version: 0.1
phases:
  install:
    commands:
      - pip install jira boto3
      - pip3 install osbot-jira osbot-gsuite osbot-aws pbx-gs-python-utils

  build:
    commands:
      - echo "**** Starting build"
      - echo "**** Running tests"
      - echo "env $aaa ...."
      - python3 osbot_gsheet_sync/tasks/update_sheet/Update_Sheet.py