version: 0.1
phases:
#  install:
#    commands:
#      - pip3 install jira boto3
#      - pip3 install elasticsearch google-api-python-client oauth2client
#      - pip3 install osbot-jira osbot-gsuite
#osbot-aws pbx-gs-python-utils

  build:
    commands:
      - echo "**** Starting build"
      - python3 osbot_gsheet_sync/tasks/update_sheet/Update_Sheet.py